# Generated by Django 3.2 on 2021-04-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endpoints',
            new_name='Endpoint',
        ),
        migrations.RenameModel(
            old_name='RawLogs',
            new_name='RawLog',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
