# Generated by Django 3.2 on 2021-04-20 18:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_auto_20210420_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('ext_ipv4', models.GenericIPAddressField(blank=True, null=True, protocol='ipv4')),
                ('int_ipv4', models.GenericIPAddressField(blank=True, null=True, protocol='ipv4')),
                ('ext_ipv6', models.GenericIPAddressField(blank=True, null=True, protocol='ipv6')),
                ('int_ipv6', models.GenericIPAddressField(blank=True, null=True, protocol='ipv6')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_heartbeat', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rawlog',
            name='endpoint_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='endpoint_id',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.AddField(
            model_name='rawlog',
            name='asset_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='endpoints.asset'),
        ),
        migrations.AddField(
            model_name='task',
            name='asset_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='endpoints.asset'),
        ),
    ]
