# Generated by Django 3.2 on 2021-04-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0007_remove_ingest_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingest',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/endpoints/ingest/<django.db.models.fields.UUIDField>/join', max_length=500),
        ),
    ]
