# Generated by Django 3.2 on 2021-04-21 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0009_auto_20210421_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b3e1a5d-7c18-404f-865a-7dd438642f2e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/endpoints/ingest/3b3e1a5d-7c18-404f-865a-7dd438642f2e/join', editable=False, max_length=500),
        ),
    ]
