# Generated by Django 3.2 on 2021-04-23 02:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0010_auto_20210421_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingest',
            name='config_files',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingest',
            name='existing_clamav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingest',
            name='home',
            field=models.CharField(default='/opt/clammer', max_length=100),
        ),
        migrations.AddField(
            model_name='ingest',
            name='log_files',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingest',
            name='login_url',
            field=models.URLField(default='http://127.0.0.1:8000/accounts/login/', max_length=500),
        ),
        migrations.AddField(
            model_name='ingest',
            name='logout_url',
            field=models.URLField(default='http://127.0.0.1:8000/accounts/logout/', max_length=500),
        ),
        migrations.AddField(
            model_name='ingest',
            name='rawlog_url',
            field=models.URLField(default='http://127.0.0.1:8000/endpoints/assets/4ab1fe95-c259-44da-8561-4bf1f03ac51f/sendrawlog/', max_length=500),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4ab1fe95-c259-44da-8561-4bf1f03ac51f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/endpoints/ingest/4ab1fe95-c259-44da-8561-4bf1f03ac51f/join', editable=False, max_length=500),
        ),
    ]
