# Generated by Django 3.2 on 2021-04-23 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0011_auto_20210423_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingest',
            name='config_files',
            field=models.CharField(blank=True, help_text='Enter ClamAV log files to monitor separated by commas.         For example, /var/log/clam.log,/var/log/freshclam.log', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('812fc064-0eed-4d02-b597-2b8b0a1cd3d8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='log_files',
            field=models.CharField(blank=True, help_text='Enter ClamAV log files to monitor separated by commas.         For example, /var/log/clam.log,/var/log/freshclam.log', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='rawlog_url',
            field=models.URLField(default='http://127.0.0.1:8000/endpoints/assets/812fc064-0eed-4d02-b597-2b8b0a1cd3d8/sendrawlog/', max_length=500),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/endpoints/ingest/812fc064-0eed-4d02-b597-2b8b0a1cd3d8/join', editable=False, max_length=500),
        ),
    ]
