# Generated by Django 3.2 on 2021-04-23 04:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0012_auto_20210423_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75dabde1-994a-4925-ab19-52b52f14f150'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='rawlog_url',
            field=models.URLField(default='http://127.0.0.1:8000/endpoints/assets/', max_length=500),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/endpoints/ingest/75dabde1-994a-4925-ab19-52b52f14f150/join', editable=False, max_length=500),
        ),
    ]
