# Generated by Django 3.2 on 2021-04-23 04:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0013_auto_20210423_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingest',
            name='log_level',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO'), ('DEBUG', 'DEBUG')], default='DEBUG', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75ce8ce8-4fc3-4b1d-9bb3-594f10da7a66'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/endpoints/ingest/75ce8ce8-4fc3-4b1d-9bb3-594f10da7a66/join', editable=False, max_length=500),
        ),
    ]
