# Generated by Django 3.2 on 2021-04-23 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0015_auto_20210423_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/endpoints/ingest/<django.db.models.fields.UUIDField>/join', editable=False, max_length=500),
        ),
    ]
